import "./globals.css";
import HEADER from "./components/HEADER";
import SmoothScroll from "./utils/SmoothScroll";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { TransitionProvider } from "./Context/TransitionContext";
import Caroussel from "./(home)/Caroussel";
import Frame from "./components/Frame";
import { ModalProvider } from "./Context/ModalContext";
import { ProjectProvider } from "./Context/ProjectContext";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SmoothScroll>
        <ModalProvider>
          <ProjectProvider>
            <TransitionProvider>
              <body className={` antialiased overflow-x-hidden `}>
                <HEADER />
                <Caroussel />
                <Frame />
                {children}
              </body>
            </TransitionProvider>
          </ProjectProvider>
        </ModalProvider>
      </SmoothScroll>
    </html>
  );
}
