import "./globals.css";
import HEADER from "./components/HEADER";
import SmoothScroll from "./utils/SmoothScroll";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Frame from "./components/Frame";
import { ModalProvider } from "./Context/ModalContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SmoothScroll>
        <ModalProvider>
          <body className={` antialiased overflow-x-hidden `}>
            <HEADER />
            <Frame />
            {children}
          </body>
        </ModalProvider>
      </SmoothScroll>
    </html>
  );
}
