import "./globals.css";
import HEADERS from "./components/HEADERS";
import SmoothScroll from "./utils/SmoothScroll";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import ShaderEffectWithNoSSR from "./components/shaders/FrontGround";
import { MobileProvider } from "./Context/isMobileContext";
import { TransitionProvider } from "./Context/TransitionContext";
import Caroussel from "./(home)/Caroussel";
import Frame from "./components/Frame";
import { ModalProvider } from "./Context/ModalContext";
import { ProjectProvider } from "./Context/ProjectContext";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SmoothScroll>
        <MobileProvider>
          <ModalProvider>
            <ProjectProvider>
              <TransitionProvider>
                <body className={` antialiased overflow-x-hidden `}>
                  <HEADERS />
                  <Caroussel />
                  <Frame />
                  {children}
                  <ShaderEffectWithNoSSR />
                </body>
              </TransitionProvider>
            </ProjectProvider>
          </ModalProvider>
        </MobileProvider>
      </SmoothScroll>
    </html>
  );
}
