export const artistsData = {
  blenk: {
    name: "BLENK",
    image: "/blenk.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK BLENK",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "Valentin’s immersion in Montpellier’s electronic music community, including a two-year residency with local promoters, quickly translated into recognition beyond his regional sphere. ",
    bio2: " His rigorously defined production style, grounded in a deep understanding of modular synthesis and classic drum machines, solidified with the launch of the Blenk project in 2018. Blenk’s work meticulously bridges established production and DJ techniques with a forward-thinking sonic perspective, prioritizing detailed sound design to sculpt techno that resonates with both atmospheric depth and driving intensity. ",
    bio3: "His output includes multiple EPs on Dustin Zahn’s Enemy Records, alongside collaborations with respected artists and labels, cementing his position within the global techno landscape. The recently released « Breaking The Loop » EP, a five-track exploration on Enemy, has already earned the approval of influential figures such as Luke Slater, Kr!z, Truncate and Rodhad, confirming his status among techno purists.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1964210748&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  confusion: {
    name: "CONFUSION",
    image: "/confusion.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK CONFUSION",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "Confusion is a Mannheim-based producer and resident DJ at Raserei, a collective dedicated to pushing the boundaries of electronic music. His sound is a dynamic blend of driving rhythms, stripped-down minimalism, and atmospheric textures. Expect a journey across tempos and subgenres, always maintaining a potent energy level.",
    bio2: " Influenced by a lifetime of drumming and a deep respect for the evolution of techno, Confusion's music draws inspiration from a wide spectrum of electronic sounds, from ambient and IDM to experimental explorations. Since 2017, he's been a key figure in the Mannheim scene, curating visionary events at Disco Zwei and bringing respected names to the region. ",
    bio3: "Beyond the club, Confusion and the Raserei crew have launched a record label and podcast series, solidifying their vision and expanding their reach. His own productions have garnered critical acclaim, with releases on labels like @canticle.records , @syxt_official , and @prx.records finding support from DVS1, Luke Slater, and Rødhåd, among others. These tracks have resonated on dancefloors worldwide, from Berghain to Bassiani.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1368083551&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  eyrah: {
    name: "EY.RAH",
    image: "/eyrah.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK EY.RAH",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "Stockholm-born, Paris-based DJ Ey.rah has established a distinctive presence within the global techno landscape. Her sound, shaped by years of immersed exploration across diverse musical terrains – from the vibrant hip-hop scenes of her youth to the evolving soundsystems of Europe, Asia and Africa – reflects a unique confluence of influences. ",
    bio2: " This eclecticism manifests in her sets, where propulsive rhythms interweave with atmospheric textures, creating a dynamic and hypnotic experience. Ey.rah’s selections are characterized by a meticulous attention to detail, revealing a profound understanding of groove and an innate ability to craft compelling narratives on the dancefloor. ",
    bio3: "Her performances, whether in intimate clubs or larger festivals, exude an understated authority, drawing listeners into her sonic world with a subtle yet undeniable magnetism.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1922756263&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  geistfrei: {
    name: "GEISTFREI",
    image: "/geistfrei.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK GEISTFREI",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "Born from a clandestine network of self-organized raves — hidden deep within Munich’s forests, abandoned buildings, and beneath the city’s concrete arteries — GEISTFREI’s artistic journey is steeped in the raw energy of the underground. ",
    bio2: " Their music has captivated audiences at renowned clubs like Blitz and Rote Sonne, and is played all over the world by names like Richie Hawtin, DVS1 and MARRON. GEISTFREI’s music not only makes your body move, but carries their inner self, echoing through the dimly lit clubs, forest glades and warehouse parties where they perform. ",
    bio3: "Their art is all about expressing their emotions while giving the listener access to their own, creating a collective healing experience on the dancefloor.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1540275052&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  ketrobinson: {
    name: "KET ROBINSON",
    image: "/ket.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK KET ROBINSON",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "Berlin-based @ket_robinson has dedicated over a decade to crafting a sound that delves into the darker recesses of techno. His productions—a kinetic surge of implacable percussion, rhythmic drums, and mesmeric melodies—draw from industrial grit and techno's inherent intensity.  ",
    bio2: " Releases on respected imprints such as MindTrip, SOMA, IMF, and Illegal Alien, coupled with support from leading figures like Richie Hawtin, Setaoc Mass, Remco Beekwilder, and Dax J, underscore his influence. While his KR Records imprint served as a vital platform for emerging artists, Ket Robinson has, in 2025, redoubled his commitment to his personal artistic trajectory.  ",
    bio3: "This renewed focus is exemplified by impactful collaborations with established artists like Kwartz and JakoJako, as well as upcoming talents such as Gannein and BFVR. With an extensive international touring history encompassing over 100 performances, from Berlin’s About Blank to prominent clubs across Buenos Aires, Paris, Shanghai, and Montreal, Robinson’s commanding presence as a DJ further solidifies his standing at the forefront of contemporary techno.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1056634198&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  lolakay: {
    name: "LOLA KAY",
    image: "/lola.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK LOLA KAY",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "Lola Kay is a talented DJ and producer based in Barcelona, originally from Minsk, Belarus. With a background as a professional dancer and a deep connection to rhythm and movement, Lola crafts sets that resonate emotionally and engage her audience on a powerful level. Her sound is known for its captivating, hypnotic journeys, seamlessly blending mental techno, hardgroove, 90s/00s techno, and Detroit techno. ",
    bio2: "A resident DJ and active member of @yo.yo.bcn and @houseofspunk collectives, Lola is dedicated to promoting inclusivity and representation within the electronic music community, creating empowering spaces that amplify marginalized voices and champion diverse artistic expressions. ",
    bio3: "With two critically acclaimed EPs, Xtasy Dance Project and Run Lola Run, released on the House of S(PUNK) label, along with a series of standout singles, Lola has firmly established herself as both a respected producer and a highly skilled DJ.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1580506267&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  manuabeca: {
    name: "MANU ABECA",
    image: "/manu.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK MANU ABECA",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "Manu abeca is a Buenos Aires-born producer based in Berlin. In his artist’s universe, emotional depth becomes a guide toward one’s salvation. ",
    bio2: " Having been involved in music from a young age, Manu brings a lot of experience and diverse influences to his DJ sets. His sounds are characterized by their harmonies, melancholic vibes and deep grooves. In addition to his DJ career, Manu’s passion for sound has evolved into a deep exploration of music production, focusing not only in dancefloor-oriented music, but also in ambient and atmospheric sounds for the soul. ",
    bio3: "In April 2024 he released his debut EP ‘inner shiftings’, marking a new chapter in his artistic journey, with many more exciting releases on the horizon.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1809410389&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  metapattern: {
    name: "META PATTERN",
    image: "/meta.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK META PATTERN",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "Metapattern, a name symbolizing « patterns of patterns, » weaves together the rich tapestry of techno from its Detroit roots to modern sub-genres. ",
    bio2: " Metapattern creates tracks that explore expressive hooks, groovy rhythms, and cinematic soundscapes. With releases on labels like FLOAT, Truncate, MORD, and HAYES, Metapattern balances the familiar with the unexpected, delivering music that’s both functional on the dance floor and deeply expressive. ",
    bio3: "Rooted in a passion for dance, Metapattern channels their energy into every beat, continually pushing the boundaries of techno.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1856907927&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  valav: {
    name: "VALAV",
    image: "/valav.webp",
    performance: "DJ SET",
    buttonTitle: "BOOK VALAV",
    city: "Montpellier",
    country: "France",
    labels: ["Truncate", "Enemy Records", "KYSH", "Mutual Rythm"],
    travel: "1 person from Marseille - France",
    bookingContact: "Alex",
    bio1: "From Venezuela to Barcelona, ValaV is making his mark on dancefloors with his signature sound, « Psygroove. » This fusion of techno, hypnotic trance, and psy trance has caught the attention of the international electronic music scene. ",
    bio2: " As co-founder of @yo.yo.bcn, one of Barcelona’s most influential queer techno parties, ValaV is committed to promoting equality, diversity, and inclusion within the LGBTQI+ community. With the release of his debut EP Dancing Memories in December 2023, supported by artists like Anetha and Nenet H, ValaV solidified his global presence. His performances have led him to iconic clubs like Kit kat, RSO in Berlin and FAWA in Paris, as well as festivals like Hivernacle and Brunch Electronik. In Spain, he’s a standout in clubs like Apolo, Razzmatazz, Moog, Laut and Florida 135, sharing the stage with figures like Richie Hawtin, Alarico, Daria Kolosova, Philipa Pacho.",
    bio3: "Every ValaV set delivers more than just music; it’s an authentic, high-energy experience that pushes the boundaries of techno while creating a space for inclusion and artistry.",
    instagram: "https://www.instagram.com/blenk_sound/",
    soundclound: "https://soundcloud.com/blenksound",
    spotify: "https://open.spotify.com/intl-fr/artist/1dkEG4atVRsDIkhriguiSp",
    iframe:
      "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/2001767439&color=%23382c25&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
  },
  // Ajoutez tous vos artistes
};
